include ../default_targets.h

test: grid_generation grid1.dockout orientflexiblemulti.dockout orientrigidmulti.dockout grid3.dockout grid4_lig_eff.dockout

grid_generation:
	cd ../grid_generation && make test

clean: clean_dock
